apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-agent-config
  namespace: default
  labels:
    app: ai-agent-service
data:
  NODE_ENV: "production"
  PORT: "3003"
  COZE_API_BASE_URL: "https://api.coze.cn"
  REQUEST_TIMEOUT: "30000"
  LOG_LEVEL: "info"
  CORS_ORIGIN: "*"
  # Health check configuration
  HEALTH_CHECK_INTERVAL: "30"
  HEALTH_CHECK_TIMEOUT: "5"
  # Rate limiting
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX_REQUESTS: "100"