apiVersion: v1
kind: Service
metadata:
  name: ai-agent-service-nodeport
  namespace: default
  labels:
    app: ai-agent-service
spec:
  type: NodePort
  ports:
  - port: 3003
    targetPort: 3003
    nodePort: 30003
    protocol: TCP
    name: http
  selector:
    app: ai-agent-service
---
apiVersion: v1
kind: Service
metadata:
  name: ai-agent-service-lb
  namespace: default
  labels:
    app: ai-agent-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3003
    protocol: TCP
    name: http
  selector:
    app: ai-agent-service